import { stat } from "mz/fs";
import { exec } from "mz/child_process";
import Task from "../task";
import { SetupSubtask } from "./setup";
import { DNS_PORT, DNS_TLD } from "../config";

const RESOLVER_PATH = "/etc/resolver/";
const RESOLVER_DOMAIN_PATH = `${RESOLVER_PATH}${DNS_TLD}`;

export default class InstallResolverTask extends Task implements SetupSubtask {
  public installMessage = `
    Install a DNS resolver that points https://*.${DNS_TLD} to localhost
  `;

  async requiresSetup(): Promise<boolean> {
    try {
      await stat(RESOLVER_DOMAIN_PATH);
    } catch (e) {
      return true;
    }

    return false;
  }

  async run() {
    await exec("sudo mkdir -p /etc/resolver/");
    await exec(`sudo sh -c "echo \\"${resolver()}\\" > ${RESOLVER_DOMAIN_PATH}"`);
  }
}

function resolver() {
  return `# Generated by Seaway
nameserver 127.0.0.1
port ${DNS_PORT}`.replace(/\n/g, "\\n");
}